services:
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: /docker/python/Dockerfile
      target: python
    ports:
      - "8001:8001"
      - "5000:5000"
      - "8888:8888"
    volumes:
      - ./python:/python
  